### ISSUE TITLE
pretrained baseline model available

### ISSUE THREAD

**Issue by jiacheng-xu** [google-research-datasets/ToTTo#1]
Hi all,
    Thanks for building this great dataset. I am looking for the pre-trained model checkpoint on ToTTo but I didn't find any model available on the readme page. Is it possible to make the Bert-to-Bert model available or the T5-fine-tuned one (https://arxiv.org/pdf/2005.10433.pdf) available? a pointer to any existing code repo is also helpful!

**Comment by ankparikh** [comment]
Sorry for the late reply (please feel free to email in the future). Is it easy for you to fine-tune the existing T5 checkpoint and see if it works?

https://github.com/google-research/text-to-text-transfer-transformer
